### ISSUE TITLE
Adding view support

### ISSUE THREAD

**Issue by CollinViz** [mevdschee/php-crud-api2#5]
Hello,

Have you ever thought to add view support ?
I add the code creating new controller called ViewController with rout /view/*
I also add it to the meta controller /metaview/
Mysql is only supported for now (It is the only DB I have at the moment)

I still have no idea how to add a pull request but will do some googleing in the weekend.
For now the view's are read only. Not sure if you really want to update views. For this project I do not think I need to do it.

I also see you have a separate project for stored procedures. I may need to pull that into this project at some time. Not sure if this is OK with you.

Thanks again for making this project it has really been a big help. 

Last thing when I build the project I get the below error. But the app runs fine. 

C:\Apache24\htdocs\php-crud-api2>php build.php
PHP Fatal error:  Uncaught Error: Class 'Tqdev\PhpCrudApi\Config' not found in C:\Apache24\htdocs\php-crud-api2\tmp_api.php:3778
Stack trace:
#0 C:\Apache24\htdocs\php-crud-api2\build.php(64): include()
#1 C:\Apache24\htdocs\php-crud-api2\build.php(72): run('C:\\Apache24\\htd...', 'src', 'api.php')
#2 {main}
  thrown in C:\Apache24\htdocs\php-crud-api2\tmp_api.php on line 3778

Fatal error: Uncaught Error: Class 'Tqdev\PhpCrudApi\Config' not found in C:\Apache24\htdocs\php-crud-api2\tmp_api.php:3778
Stack trace:
#0 C:\Apache24\htdocs\php-crud-api2\build.php(64): include()
#1 C:\Apache24\htdocs\php-crud-api2\build.php(72): run('C:\\Apache24\\htd...', 'src', 'api.php')
#2 {main}
  thrown in C:\Apache24\htdocs\php-crud-api2\tmp_api.php on line 3778

**Comment by CollinViz** [comment]
Hi,

Got the build to work - I add a file in the wrong directory for testing.

**Comment by mevdschee** [comment]
>Have you ever thought to add view support ?

Yes, version 1 supports list calls on views. I want to add it, but it is not in there yet.

>I add the code creating new controller called ViewController with rout /view/*
>I also add it to the meta controller /metaview/
>Mysql is only supported for now (It is the only DB I have at the moment)

Great! If you share the code, then I can see whether or not it is useful to me.
